name: "Beszel Agent Dev Branch"
description: "Beszel Agent for HASSIO (Dev Branch)"
version: "0.0.6"
slug: "beszel_agent"
init: false
legacy: true
arch:
  - amd64
  - armhf
  - armv7
options:
  KEY: "default_value"
  ports: 45876
schema:
  KEY: "str"
  ports: "int"
