name: "Beszel Agent Dev Branch"
description: "Beszel Agent for HASSIO"
version: "250117-3"
slug: "beszel_agent_dev"
init: false
host_network: true
docker_api: true
arch:
  - amd64
  - armhf
  - armv7
options:
  KEY: "default_value"
schema:
  KEY: "password"
ports:
  45876/tcp: 45876
